const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';
test('single migration preserves live RLS, bounds direct writes and enforces consent/quota/revocation',async()=>{
 const db=new PGlite();const sql=name=>fs.readFileSync(path.join(__dirname,'../../supabase/migrations',name),'utf8');
 try {
  await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
   create schema auth;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb);
   create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
   grant usage on schema auth to anon,authenticated;`);
  for(const f of ['001_create_profiles_table.sql','002_add_location_preferences_to_profiles.sql','004_create_profile_career_entries.sql'])await db.exec(sql(f));
  await db.exec(`alter table profiles enable row level security;grant select,insert,update,delete on profiles to authenticated;
   create policy existing_owner_policy on profiles for all to authenticated using(auth.uid()=id) with check(auth.uid()=id);
   insert into auth.users values('${a}','a@example.test','{}'),('${b}','b@example.test','{}');`);
  await db.exec(sql('008_privacy_consent_and_limits.sql'));await db.exec(sql('008_privacy_consent_and_limits.sql'));
  assert.equal((await db.query("select count(*)::int as n from pg_policies where policyname='existing_owner_policy'")).rows[0].n,1);
  await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${a}',false)`);
  await assert.rejects(db.exec("select set_ai_consent('gemini','2026-09-v1',true)"),/unavailable/);
  await assert.rejects(db.exec(`select reserve_ai_call('${a}','gemini')`),/permission denied/);
  await assert.rejects(db.exec(`insert into ai_consents values('${a}','gemini','2026-09-v1',true,now(),null,now())`),/permission denied/);
  assert.equal((await db.query('select * from profiles')).rows.length,1);
  await assert.rejects(db.exec(`update profiles set bio=repeat('x',5001) where id='${a}'`),/personal_data_limits/);
  await db.exec(`insert into profile_career_entries(user_id,kind,title,organization,start_month,is_current) select '${a}','work','Developer','Test','2024-01',true from generate_series(1,200)`);
  await assert.rejects(db.exec(`insert into profile_career_entries(user_id,kind,title,organization,start_month,is_current) values('${a}','work','More','Test','2024-01',true)`),/quota/);
  await db.exec('delete from profile_career_entries where id=(select id from profile_career_entries limit 1)');
  await db.exec(`insert into profile_career_entries(user_id,kind,title,organization,start_month,is_current) values('${a}','work','Replacement','Test','2024-01',true)`);
  await db.exec("reset role;update ai_privacy_notices set notice_sv='Reviewed Swedish notice',notice_en='Reviewed English notice',enabled=true where provider='gemini';update ai_budget set per_user_limit=2,daily_limit=2");
  await db.exec(`set role authenticated;select set_ai_consent('gemini','2026-09-v1',true)`);
  assert.equal((await db.query('select * from ai_consent_receipts')).rows.length,1);
  await db.exec(`select set_config('request.jwt.claim.sub','${b}',false)`);
  assert.equal((await db.query('select * from ai_consents')).rows.length,0);
  await db.exec('reset role;set role service_role');
  const first=(await db.query(`select reserve_ai_call('${a}','gemini') as ticket`)).rows[0].ticket;assert.ok(first);
  assert.equal((await db.query(`select reserve_ai_call('${a}','gemini') as ticket`)).rows[0].ticket,null);
  await db.exec(`select release_ai_call('${a}','${b}')`);
  assert.equal((await db.query(`select reserve_ai_call('${a}','gemini') as ticket`)).rows[0].ticket,null);
  await db.exec(`select release_ai_call('${a}','${first}');reset role;set role authenticated;select set_config('request.jwt.claim.sub','${a}',false);select set_ai_consent('gemini','',false);reset role;set role service_role`);
  assert.equal((await db.query(`select reserve_ai_call('${a}','gemini') as ticket`)).rows[0].ticket,null);
  await db.exec("reset role");
  await assert.rejects(db.exec("update ai_privacy_notices set notice_sv='Changed' where provider='gemini'"),/new notice version/);
  await db.exec(`set role authenticated;select set_ai_consent('gemini','2026-09-v1',true);reset role;set role service_role`);
  const second=(await db.query(`select reserve_ai_call('${a}','gemini') as ticket`)).rows[0].ticket;assert.ok(second);
  await db.exec(`select release_ai_call('${a}','${second}')`);
  assert.equal((await db.query(`select reserve_ai_call('${a}','gemini') as ticket`)).rows[0].ticket,null);
  await db.exec('reset role;set role anon');await assert.rejects(db.exec("select set_ai_consent('gemini','2026-09-v1',true)"),/permission denied/);
  await db.exec(`reset role;delete from auth.users where id='${a}'`);
  for(const table of ['ai_consents','ai_consent_receipts','ai_usage','aplifyr_career_counts'])assert.equal((await db.query('select * from '+table)).rows.length,0);
 }finally{await db.close();}
});
